name: Tests
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.ref }}
  cancel-in-progress: false

permissions:
  contents: read # checkout

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Tests
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cache Rust Build Artifacts
        uses: https://data.forgejo.org/actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install System Dependencies
        shell: bash
        run: .forgejo/scripts/install-deps.sh jq pkg-config perl

      - name: Install Rust
        shell: bash
        run: .forgejo/scripts/install-rust.sh nightly
      - name: Run Tests
        shell: bash
        run: |
          set -euxo pipefail
          . "$HOME/.cargo/env"
          cargo +nightly test --locked --workspace --features vendored
